module.exports = {
	plugins: ['stylelint-order'],
	rules: {
		'color-no-invalid-hex': true,
		'function-calc-no-invalid': true,
		'function-calc-no-unspaced-operator': true,
		'function-linear-gradient-no-nonstandard-direction': true,
		'string-no-newline': true,
		'unit-no-unknown': true,
		'keyframe-declaration-no-important': true,
		'declaration-block-no-duplicate-properties': [true, { ignore: ['consecutive-duplicates'] }],
		'declaration-block-no-shorthand-property-overrides': true,
		'block-no-empty': true,
		'selector-pseudo-class-no-unknown': [true, { ignorePseudoClasses: ['export', 'import', 'global', 'local', 'external'] }],
		'selector-pseudo-element-no-unknown': true,
		'selector-type-no-unknown': true,
		'at-rule-no-unknown': null,
		'comment-no-empty': true,
		'no-duplicate-at-import-rules': true,
		'no-duplicate-selectors': true,
		'no-empty-source': true,
		'no-extra-semicolons': true,
		'no-invalid-double-slash-comments': true,
		'alpha-value-notation': 'number',
		'hue-degree-notation': 'angle',
		'color-function-notation': 'modern',
		'color-named': 'never',
		'length-zero-no-unit': true,
		'font-weight-notation': 'numeric',
		'function-url-no-scheme-relative': true,
		'number-max-precision': 2,
		'shorthand-property-no-redundant-values': true,
		'value-no-vendor-prefix': null,
		'property-no-vendor-prefix': null,
		'declaration-block-no-redundant-longhand-properties': true,
		'declaration-no-important': true,
		'declaration-block-single-line-max-declarations': 1,
		'selector-max-empty-lines': 0,
		'selector-no-qualifying-type': true,
		'selector-no-vendor-prefix': true,
		'selector-pseudo-element-colon-notation': 'double',
		'media-feature-name-no-vendor-prefix': true,
		'at-rule-no-vendor-prefix': true,
		'max-nesting-depth': 4,
		'no-unknown-animations': true,
		'color-hex-case': 'lower',
		'color-hex-length': 'short',
		'font-family-name-quotes': 'always-unless-keyword',
		'function-comma-newline-after': 'never-multi-line',
		'function-comma-newline-before': 'never-multi-line',
		'function-comma-space-after': 'always',
		'function-comma-space-before': 'never',
		'function-max-empty-lines': 0,
		'function-name-case': 'lower',
		'function-parentheses-newline-inside': 'never-multi-line',
		'function-parentheses-space-inside': 'never',
		'function-url-quotes': 'always',
		'function-whitespace-after': 'always',
		'number-leading-zero': 'never',
		'number-no-trailing-zeros': true,
		'string-quotes': 'single',
		'unit-case': 'lower',
		'value-keyword-case': 'lower',
		'value-list-comma-newline-after': 'never-multi-line',
		'value-list-comma-newline-before': 'never-multi-line',
		'value-list-comma-space-after': 'always',
		'value-list-comma-space-before': 'never',
		'value-list-max-empty-lines': 0,
		'custom-property-empty-line-before': 'never',
		'property-case': 'lower',
		'declaration-bang-space-after': 'never',
		'declaration-colon-newline-after': 'always-multi-line',
		'declaration-colon-space-after': 'always-single-line',
		'declaration-colon-space-before': 'never',
		'declaration-block-semicolon-newline-after': 'always-multi-line',
		'declaration-block-semicolon-newline-before': 'never-multi-line',
		'declaration-block-semicolon-space-after': 'always-single-line',
		'declaration-block-semicolon-space-before': 'never',
		'declaration-block-trailing-semicolon': 'always',
		'block-closing-brace-empty-line-before': 'never',
		'block-closing-brace-newline-after': 'always',
		'block-closing-brace-newline-before': 'always-multi-line',
		'block-closing-brace-space-before': 'always-single-line',
		'block-opening-brace-newline-after': 'always',
		'block-opening-brace-space-after': 'always-single-line',
		'block-opening-brace-space-before': 'always',
		'selector-attribute-brackets-space-inside': 'never',
		'selector-attribute-operator-space-after': 'never',
		'selector-attribute-operator-space-before': 'never',
		'selector-attribute-quotes': 'always',
		'selector-combinator-space-after': 'always',
		'selector-combinator-space-before': 'always',
		'selector-descendant-combinator-no-non-space': true,
		'selector-pseudo-class-case': 'lower',
		'selector-pseudo-class-parentheses-space-inside': 'never',
		'selector-pseudo-element-case': 'lower',
		'selector-type-case': 'lower',
		'selector-list-comma-newline-after': 'always-multi-line',
		'selector-list-comma-newline-before': 'never-multi-line',
		'selector-list-comma-space-after': 'always-single-line',
		'selector-list-comma-space-before': 'never',
		'rule-empty-line-before': 'always',
		'media-feature-colon-space-after': 'always',
		'media-feature-colon-space-before': 'never',
		'media-feature-name-case': 'lower',
		'media-feature-parentheses-space-inside': 'never',
		'media-feature-range-operator-space-after': 'always',
		'media-feature-range-operator-space-before': 'always',
		'media-query-list-comma-space-after': 'always-single-line',
		'media-query-list-comma-space-before': 'never',
		'at-rule-empty-line-before': 'always',
		'at-rule-name-case': 'lower',
		'at-rule-name-space-after': 'always',
		'at-rule-semicolon-space-before': 'never',
		indentation: 'tab',
		'max-empty-lines': 1,
		'max-line-length': 150,
		'no-eol-whitespace': true,
		'no-missing-end-of-source-newline': true,
		'no-empty-first-line': true,
		'order/order': [['custom-properties', 'declarations'], { disableFix: true }],
		'order/properties-order': [
			{
				emptyLineBefore: 'always',
				properties: ['position', 'z-index', 'top', 'right', 'bottom', 'left'],
			},
			{
				emptyLineBefore: 'always',
				properties: ['display', 'visibility', 'float', 'clear', 'flex', 'flex-basis', 'flex-direction', 'flex-flow', 'flex-grow', 'flex-shrink', 'flex-wrap', 'align-content', 'align-items', 'align-self', 'justify-content', 'order'],
			},
			{
				emptyLineBefore: 'always',
				properties: ['grid', 'grid-after', 'grid-area', 'grid-auto-columns', 'grid-auto-flow', 'grid-auto-rows', 'grid-before', 'grid-column', 'grid-column-end', 'grid-column-gap', 'grid-column-start', 'grid-columns', 'grid-end', 'grid-gap', 'grid-row', 'grid-row-end', 'grid-row-gap', 'grid-row-start', 'grid-rows', 'grid-start', 'grid-template', 'grid-template-areas', 'grid-template-columns', 'grid-template-rows'],
			},
			{
				emptyLineBefore: 'always',
				properties: ['width', 'min-width', 'max-width', 'height', 'min-height', 'max-height'],
			},
			{
				emptyLineBefore: 'always',
				properties: ['box-sizing', 'margin', 'margin-top', 'margin-right', 'margin-bottom', 'margin-left', 'padding', 'padding-top', 'padding-right', 'padding-bottom', 'padding-left', 'border', 'border-top', 'border-right', 'border-bottom', 'border-left', 'border-width', 'border-top-width', 'border-right-width', 'border-bottom-width', 'border-left-width', 'border-style', 'border-top-style', 'border-right-style', 'border-bottom-style', 'border-left-style', 'border-radius', 'border-top-left-radius', 'border-top-right-radius', 'border-bottom-right-radius', 'border-bottom-left-radius', 'border-color', 'border-top-color', 'border-right-color', 'border-bottom-color', 'border-left-color', 'outline', 'outline-color', 'outline-offset', 'outline-style', 'outline-width'],
			},
			{
				emptyLineBefore: 'always',
				properties: ['opacity', 'background', 'background-attachment', 'background-clip', 'background-color', 'background-image', 'background-repeat', 'background-position', 'background-size', 'box-shadow', 'fill'],
			},
			{
				emptyLineBefore: 'always',
				properties: ['overflow', 'overflow-x', 'overflow-y'],
			},
			{
				emptyLineBefore: 'always',
				properties: ['clip', 'zoom'],
			},
			{
				emptyLineBefore: 'always',
				properties: ['columns', 'column-gap', 'column-fill', 'column-rule', 'column-span', 'column-count', 'column-width'],
			},
			{
				emptyLineBefore: 'always',
				properties: ['table-layout', 'empty-cells', 'caption-side', 'border-spacing', 'border-collapse', 'list-style', 'list-style-position', 'list-style-type', 'list-style-image'],
			},
			{
				emptyLineBefore: 'always',
				properties: ['transform', 'transform-box', 'transform-origin', 'transform-style', 'backface-visibility', 'perspective', 'perspective-origin', 'transition', 'transition-property', 'transition-duration', 'transition-timing-function', 'transition-delay'],
			},
			{
				emptyLineBefore: 'always',
				properties: ['animation', 'animation-name', 'animation-duration', 'animation-play-state', 'animation-timing-function', 'animation-delay', 'animation-iteration-count', 'animation-direction'],
			},
			{
				emptyLineBefore: 'always',
				properties: ['stroke-width', 'stroke-linecap', 'stroke-dasharray', 'stroke-dashoffset', 'stroke'],
			},
			{
				emptyLineBefore: 'always',
				properties: ['color', 'font', 'font-family', 'font-size', 'font-size-adjust', 'font-smoothing', 'font-stretch', 'font-style', 'font-variant', 'font-weight', 'letter-spacing', 'line-height', 'list-style', 'text-align', 'text-align-last', 'text-decoration', 'text-decoration-color', 'text-decoration-line', 'text-decoration-style', 'text-indent', 'text-justify', 'text-overflow', 'text-overflow-ellipsis', 'text-overflow-mode', 'text-rendering', 'text-outline', 'text-shadow', 'text-transform', 'text-wrap', 'word-wrap', 'word-break', 'vertical-align', 'white-space', 'word-spacing', 'hyphens', 'text-emphasis', 'text-emphasis-color', 'text-emphasis-style', 'text-emphasis-position', 'font-emphasize', 'font-emphasize-position', 'font-emphasize-style', 'src'],
			},
			{
				emptyLineBefore: 'always',
				properties: ['tab-size', 'counter-reset', 'counter-increment', 'resize', 'cursor', 'pointer-events', 'speak', 'user-select', 'nav-index', 'nav-up', 'nav-right', 'nav-down', 'nav-left'],
			},
		],
	},
};
